---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner01
  namespace: ethereum-net
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner02
  namespace: ethereum-net
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner03
  namespace: ethereum-net
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-bootnode
  namespace: ethereum-net
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #creationTimestamp: null
  namespace: ethereum-net
  labels:
    name: volume-ethmonitor
  name: volume-ethmonitor
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
#status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ethereum-net
  labels:
    name: volume-mongodb
  name: volume-mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
#status: {}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: miner01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    #type: DirectoryOrCreate
    path: "/datas/miner01"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: miner02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    #type: DirectoryOrCreate
    path: "/datas/miner02"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: miner03
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    #type: DirectoryOrCreate
    path: "/datas/miner03"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bootnode
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    #type: DirectoryOrCreate
    path: "/datas/bootnode"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    #type: DirectoryOrCreate
    path: "/datas/mongodb"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitor
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    #type: DirectoryOrCreate
    path: "/datas/monitor"
